name: Docs build and deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.8"

      - name: Install Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - uses: julia-actions/cache@v3

      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          cd docs;
          julia --color=yes makedocs.jl

      - name: Upload site as artifact
        uses: actions/upload-artifact@v7
        with:
          name: Docs build
          path: ./docs/build
